/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */

/* Define if you have the editline library */
#define HAVE_LIBEDITLINE 1

/* Name of package */
#define PACKAGE "pknotsRG"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "Peter Steffen"

/* Define to the full name of this package. */
#define PACKAGE_NAME "pknotsRG"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "pknotsRG 1.3"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "pknotsRG"

/* Define to the version of this package. */
#define PACKAGE_VERSION "1.3"

/* Release date of current version */
#define RELEASE_DATE "Sep. 19. 2006"

/* Version number of package */
#define VERSION "1.3"
